import { db } from '@/db';
import { menuItems } from '@/db/schema';

async function main() {
    const sampleMenuItems = [
        {
            name: 'Masala Dosa',
            description: 'Crispy South Indian crepe with spicy potato filling and coconut chutney',
            price: 35,
            category: 'snacks',
            imageUrl: 'https://images.unsplash.com/photo-1630383249896-424e482df921?w=400',
            available: true,
            createdAt: new Date('2024-01-10').toISOString(),
        },
        {
            name: 'Plain Dosa',
            description: 'Traditional crispy rice and lentil crepe served with sambar and chutney',
            price: 25,
            category: 'snacks',
            imageUrl: 'https://images.unsplash.com/photo-1694159449763-c2eaf9eff966?w=400',
            available: true,
            createdAt: new Date('2024-01-10').toISOString(),
        },
        {
            name: 'Idli (3 pieces)',
            description: 'Soft steamed rice cakes served with sambar and coconut chutney',
            price: 20,
            category: 'snacks',
            imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=400',
            available: true,
            createdAt: new Date('2024-01-11').toISOString(),
        },
        {
            name: 'Medu Vada (2 pieces)',
            description: 'Crispy fried lentil donuts with a soft fluffy center',
            price: 20,
            category: 'snacks',
            imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400',
            available: true,
            createdAt: new Date('2024-01-11').toISOString(),
        },
        {
            name: 'Samosa (2 pieces)',
            description: 'Golden fried pastry filled with spiced potatoes and peas',
            price: 15,
            category: 'snacks',
            imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400',
            available: true,
            createdAt: new Date('2024-01-12').toISOString(),
        },
        {
            name: 'Pav Bhaji',
            description: 'Spicy mixed vegetable curry served with buttered bread rolls',
            price: 40,
            category: 'snacks',
            imageUrl: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400',
            available: true,
            createdAt: new Date('2024-01-12').toISOString(),
        },
        {
            name: 'Bhel Puri',
            description: 'Tangy street food mix of puffed rice, vegetables, and tamarind chutney',
            price: 25,
            category: 'snacks',
            imageUrl: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?w=400',
            available: true,
            createdAt: new Date('2024-01-13').toISOString(),
        },
        {
            name: 'Paneer Pakora',
            description: 'Crispy fried cottage cheese fritters with mint chutney',
            price: 35,
            category: 'snacks',
            imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400',
            available: false,
            createdAt: new Date('2024-01-13').toISOString(),
        },
        {
            name: 'Aloo Bonda',
            description: 'Deep-fried potato dumplings coated in chickpea flour',
            price: 15,
            category: 'snacks',
            imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400',
            available: true,
            createdAt: new Date('2024-01-14').toISOString(),
        },
        {
            name: 'Gobi Manchurian',
            description: 'Indo-Chinese crispy cauliflower florets in spicy tangy sauce',
            price: 40,
            category: 'snacks',
            imageUrl: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=400',
            available: true,
            createdAt: new Date('2024-01-14').toISOString(),
        },
        {
            name: 'Chicken Biryani',
            description: 'Fragrant basmati rice with tender chicken pieces and aromatic spices',
            price: 120,
            category: 'meals',
            imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400',
            available: true,
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            name: 'Veg Biryani',
            description: 'Aromatic rice layered with mixed vegetables and fragrant spices',
            price: 80,
            category: 'meals',
            imageUrl: 'https://images.unsplash.com/photo-1642821373181-696a54913e93?w=400',
            available: true,
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            name: 'Veg Fried Rice',
            description: 'Indo-Chinese style fried rice with mixed vegetables and soy sauce',
            price: 60,
            category: 'meals',
            imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400',
            available: true,
            createdAt: new Date('2024-01-16').toISOString(),
        },
        {
            name: 'Curd Rice',
            description: 'Cooling comfort food with rice mixed in creamy yogurt and tempering',
            price: 50,
            category: 'meals',
            imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400',
            available: true,
            createdAt: new Date('2024-01-16').toISOString(),
        },
        {
            name: 'Lemon Rice',
            description: 'Tangy South Indian rice dish with lemon juice, peanuts, and curry leaves',
            price: 45,
            category: 'meals',
            imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400',
            available: true,
            createdAt: new Date('2024-01-17').toISOString(),
        },
        {
            name: 'Sambar Rice',
            description: 'Rice mixed with flavorful lentil and vegetable stew',
            price: 50,
            category: 'meals',
            imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400',
            available: true,
            createdAt: new Date('2024-01-17').toISOString(),
        },
        {
            name: 'Paneer Butter Masala with Naan',
            description: 'Cottage cheese in rich creamy tomato gravy served with butter naan',
            price: 100,
            category: 'meals',
            imageUrl: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400',
            available: false,
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            name: 'Chana Masala with Rice',
            description: 'Spicy chickpea curry served with steamed rice',
            price: 70,
            category: 'meals',
            imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400',
            available: true,
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            name: 'Veg Pulao',
            description: 'Mildly spiced rice cooked with mixed vegetables and whole spices',
            price: 65,
            category: 'meals',
            imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400',
            available: true,
            createdAt: new Date('2024-01-19').toISOString(),
        },
        {
            name: 'Tea (Chai)',
            description: 'Hot masala tea brewed with milk, spices, and fresh ginger',
            price: 10,
            category: 'beverages',
            imageUrl: 'https://images.unsplash.com/photo-1597318167208-37465353c989?w=400',
            available: true,
            createdAt: new Date('2024-01-20').toISOString(),
        },
        {
            name: 'Filter Coffee',
            description: 'South Indian style strong coffee with frothy milk',
            price: 15,
            category: 'beverages',
            imageUrl: 'https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=400',
            available: true,
            createdAt: new Date('2024-01-20').toISOString(),
        },
        {
            name: 'Fresh Lemon Juice',
            description: 'Refreshing lime juice with a hint of salt and sugar',
            price: 20,
            category: 'beverages',
            imageUrl: 'https://images.unsplash.com/photo-1523677011781-c91d1bbe2f9d?w=400',
            available: true,
            createdAt: new Date('2024-01-21').toISOString(),
        },
        {
            name: 'Mango Juice',
            description: 'Sweet and tangy fresh mango juice',
            price: 30,
            category: 'beverages',
            imageUrl: 'https://images.unsplash.com/photo-1519985176271-adb1088fa94c?w=400',
            available: false,
            createdAt: new Date('2024-01-21').toISOString(),
        },
        {
            name: 'Cold Drink (Coke/Pepsi)',
            description: 'Chilled carbonated soft drink',
            price: 20,
            category: 'beverages',
            imageUrl: 'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=400',
            available: true,
            createdAt: new Date('2024-01-22').toISOString(),
        },
        {
            name: 'Sweet Lassi',
            description: 'Creamy yogurt-based drink sweetened to perfection',
            price: 25,
            category: 'beverages',
            imageUrl: 'https://images.unsplash.com/photo-1567630711303-1c32cdc3aad8?w=400',
            available: true,
            createdAt: new Date('2024-01-22').toISOString(),
        },
        {
            name: 'Buttermilk',
            description: 'Cooling spiced yogurt drink with curry leaves and ginger',
            price: 15,
            category: 'beverages',
            imageUrl: 'https://images.unsplash.com/photo-1583032015879-d89a2c5e4e64?w=400',
            available: true,
            createdAt: new Date('2024-01-23').toISOString(),
        },
        {
            name: 'Vanilla Ice Cream',
            description: 'Creamy vanilla ice cream scoop',
            price: 30,
            category: 'desserts',
            imageUrl: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400',
            available: true,
            createdAt: new Date('2024-01-24').toISOString(),
        },
        {
            name: 'Gulab Jamun (2 pieces)',
            description: 'Soft milk solid dumplings soaked in rose-flavored sugar syrup',
            price: 25,
            category: 'desserts',
            imageUrl: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=400',
            available: true,
            createdAt: new Date('2024-01-24').toISOString(),
        },
        {
            name: 'Kulfi',
            description: 'Traditional Indian ice cream with cardamom and pistachios',
            price: 35,
            category: 'desserts',
            imageUrl: 'https://images.unsplash.com/photo-1631380798757-1068d1f46bdc?w=400',
            available: true,
            createdAt: new Date('2024-01-25').toISOString(),
        },
        {
            name: 'Ras Malai (2 pieces)',
            description: 'Soft cottage cheese dumplings in sweetened creamy milk',
            price: 40,
            category: 'desserts',
            imageUrl: 'https://images.unsplash.com/photo-1588307760717-56c63f29890b?w=400',
            available: true,
            createdAt: new Date('2024-01-25').toISOString(),
        },
        {
            name: 'Jalebi',
            description: 'Crispy deep-fried sweet spirals soaked in sugar syrup',
            price: 20,
            category: 'desserts',
            imageUrl: 'https://images.unsplash.com/photo-1621303837174-89787a7d4729?w=400',
            available: true,
            createdAt: new Date('2024-01-26').toISOString(),
        },
    ];

    await db.insert(menuItems).values(sampleMenuItems);
    
    console.log('✅ Menu items seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});